spring.application.name=daily-planner
# 1. Konfiguracja bazy danych H2 w pamięci RAM
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# 2. Włączenie konsoli H2 w przeglądarce pod adresem localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# 3. Pokazywanie zapytań SQL generowanych przez JPA w konsoli IntelliJ
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true